# ------------------------------------------------------------------------
# Copyright (c) 2021 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: vdv_RVRT
model_type: ModelRVRT
manual_seed: 0
num_gpu: auto
reload: true
retrain: False
flowrefine_ratio: 0.25
offset_ratio: 0.25
softconv_ratio: 0.5
no_fix_flow: true

network_g:
  type: RVRT
  upscale: 1
  clip_size: 2
  img_size: [ 2, 64, 64 ]
  window_size: [ 2, 8, 8 ]
  num_blocks: [ 1, 2, 1 ]
  depths: [ 2, 2, 2 ]
  embed_dims: [ 192, 192, 192 ]
  num_heads: [ 6, 6, 6 ]
  inputconv_groups: [ 1, 3, 3, 3, 3, 3 ]
  spynet_path: "model_zoo/rvrt/spynet_sintel_final-3d2a1287.pth"
  deformable_groups: 12
  attention_heads: 12
  attention_window: [ 3, 3 ]
  use_checkpoint_attn: false
  use_checkpoint_ffn: false
  no_checkpoint_attn_blocks: [ ]
  no_checkpoint_ffn_blocks: [ ]
  cpu_cache_length: 100


datasets:
  train:
    name: VideoDeblur
    type: DeblurRecurrentDataset
    dataroot_gt: ./datasets/VDV/train/GT
    dataroot_lq: ./datasets/VDV/train/blur
    dataroot_pm: ./datasets/VDV/train/PredictMask
    dataroot_hm: ./datasets/VDV/train/HardMask
    dataroot_fw_residual: ./datasets/VDV/train/fw_residual
    dataroot_bw_residual: ./datasets/VDV/train/bw_residual

    meta_info_file: basicsr/data/meta_info/VDV_train.txt
    val_partition: ~
    test_mode: False
    io_backend:
      type: disk
    file_end: png
    cache_data: false

    num_frame: 10
    scale: 1
    gt_size: 256
    interval_list: [2]
    random_reverse: false
    use_hflip: True
    use_rot: false
    force_blur_region_p: 0.99

    load_residual_flow: False
    load_predict_mask: False
    # data loader
    num_worker_per_gpu: 2
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 100
    prefetch_mode: ~
    

  val:
    name: vdv
    type: VideoRecurrentTestDatasetlocal
    dataroot_gt: ./datasets/VDV/test/GT
    dataroot_lq: ./datasets/VDV/test/blur
    dataroot_pm: ./datasets/VDV/test/PredictMask
    dataroot_hm: ./datasets/VDV/test/HardMask
    dataroot_fw_residual: ./datasets/VDV/test/fw_residual
    dataroot_bw_residual: ./datasets/VDV/test/bw_residual
    scale_factor: 4

    cache_data: false
    io_backend:
      type: disk

    num_frame: 20

path:
  pretrain_network_g: model_zoos/RVRT_DVD_16frames.pth
  strict_load_g: true
  resume_state: ~

train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 20000
    eta_min: !!float 1e-7

  total_iter: 20000
  warmup_iter: 1000 # no warm up
  fix_flow: 10000

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: 1000
  save_img: false
  crop_size: 256
  max_minibatch: 1

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: ssim_calculate
    weighted_psnr:
      type: calculate_weighted_psnr
      crop_border: 0
      test_y_channel: false
    weighted_ssim:
        type: weighted_ssim_calculate
    
# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: 2500
  use_tb_logger: true
  show_tf_imgs_freq: 500
  wandb:
    project: ~
    resume_id: ~
    wandb_name: ~


# dist training settings
dist_params:
  backend: nccl
  port: 29510
find_unused_parameters: True
